/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.penchev.susi;

public class SUSI {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
